### ISSUE TITLE
试了一下不能解析中文

### ISSUE THREAD

**Issue by biyaa** [wangzhione/scjson#1]
![image](https://user-images.githubusercontent.com/3362347/34635460-933dfe0c-f2ca-11e7-844f-b308f6c0796a.png)

**Comment by wangzhione** [comment]
是这样的, 内部对中文解析都是走 UTF-8 编码 (可以看 scjosn 中 _parse_string 函数)

**Comment by wangzhione** [comment]
你可以这样测试
// test scjson gbk 
//
void test_scjson_gbk(void) {
    // winds gbk 环境加 u8. linux 环境默认 u8
    char * json = u8"{ \"name\" : \"n好h吗8\" }";

    printf("json :\n %s\n", json);

    // 先生成 json 对象
    cjson_t root = cjson_newstr(json);
    CERR_IF(NULL == root);

    cjson_t name = cjson_getobject(root, "name");
    printf("name -> %s\n", name->vs);
    // 输出 UTF-8 到文件中
    tstr_fwrites("logs/jstr.log", name->vs);

    // 通过 json 对象构建 json 串内容
    char * jstr = cjson_getstr(root);
    CERR_IF(NULL == jstr);

    //合法范围直接输出 内容
    printf("jstr :\n %s\n", jstr);

    // 释放内存
    free(jstr);
    cjson_delete(root);
}
 看 logs/jstr.log 文本显示, 就是所要文本.

**Comment by wangzhione** [comment]
额外扯一点, 这个库. 
以后会升级个v2版本, 不再走递归下降分析. 采用"慢启动" 使用时候解析(get 时候).
有问题欢迎再交流.

**Comment by wangzhione** [comment]
那个是我的问题. 触发了下面一个 BUG
char c -> sprintf(ptr, "u%04x", c) c 是有符号的, 导致错误的编码.
目前应该修正
unsigned char c 就正常了. 
谢谢了.
